---

- hosts : all
  become: true
  gather_facts: true #default true
  # pre_tasks:
  # - name: install updates
    # tags: always
    # apt:
      # # upgrade: dist
      # update_cache: yes
    # when: ansible_distribution in [ "Debian", "Ubuntu" ]
    

- hosts: workstations
  become: true
  gather_facts: false 
  tasks:
    - name: remove unzip
      package:
        name: unzip
        state: absent

    - name: remove file terraform
      ansible.builtin.file:
        path: /usr/local/bin/terraform
        state: absent

      
- hosts: web_servers
  become: true
  gather_facts: false 
  tasks:
    - name: remove apache php for ubuntu
      tags: apache,apache2,ubuntu,webserver
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: remove file default_site html file
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent


- hosts: db_servers
  become: true
  gather_facts: false
  tasks:
    - name: remove mariadb package
      tags: db,mariadb,ubuntu
      apt:
        name: 
          - mariadb-server
        state: absent
      when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  gather_facts: false
  tasks:
    - name: remove samba package
      tags: samba
      apt:
        name: 
          - samba
        state: absent
      when: ansible_distribution == "Ubuntu"

