---

- hosts : all
  become: true
  pre_tasks:
  - name: install updates
    tags: always
    apt:
      # upgrade: dist
      update_cache: yes
    when: ansible_distribution in [ "Debian", "Ubuntu" ]


- hosts: web_servers
  become: true
  gather_facts: no #default yes
  tasks:
    - name: install apache php for ubuntu
      tags: apache,apache2,ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  gather_facts: no
  tasks:
    - name: install mariadb package
      tags: db,mariadb,ubuntu
      apt:
        name: 
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  gather_facts: no
  tasks:
    - name: install samba package
      tags: samba
      apt:
        name: 
          - samba
        state: latest
      when: ansible_distribution == "Ubuntu"

