---

- hosts : all
  become: true
  gather_facts: true                                            # default: true | berfungsi sebagai mencari fakta di remote server/seperti ping
  pre_tasks:
  - name: install updates
    tags: [ always, update ]
    apt:
      # upgrade: dist
      update_cache: yes
    changed_when: false                                         # menyembunyikan output dari perintah
    when: ansible_distribution in [ "Debian", "Ubuntu" ]


- hosts: all
  become: true
  gather_facts: false  
  roles:
    - base


- hosts: workstations
  become: true
  gather_facts: true 
  roles:
    - workstations
      
        
- hosts: web_servers
  become: true
  gather_facts: true
  roles:
    - web_servers
    

- hosts: db_servers
  become: true
  gather_facts: false
  roles:
    - db_servers


- hosts: file_servers
  become: true
  gather_facts: false
  roles:
    - file_servers
