
- name: install apache-php for ubuntu
  tags: apache,httpd,php
  apt:
    name:
      - "{{ apache_package_name }}"                          # variable didefinisikan di folder host_vars
      - "{{ php_package_name }}"
    state: latest
  # when: ansible_distribution in [ "Debian", "Ubuntu" ]

- name: start apache2
  tags: apache,apache2,ubuntu
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
  # when: ansible_distribution in [ "Debian", "Ubuntu" ]

- name: change email address for admin
  tags: apache,httpd
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^\sServerAdmin'
    line: ServerAdmin webserver212@somewhere.net
  when: ansible_distribution in [ "Debian", "Ubuntu" ]
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
